### ISSUE TITLE
Misc Bullshit 2, Electric Boogaloo

### ISSUE THREAD

**Issue by ArtOfShred** [DakJaniels/LuiExtended#108]
Random easy crap to do when I'm not at work:

SCB:
- [x] MOVE WEREWOLF HANDLER TO SEPARATE LUA (Werewolf.lua)
- [x] MOVE DEBUG HANDLER TO SEPARATE LUA (Debug.lua)
- [x] MOVE MOUNT/COLLECTIBLE TO SEPARATE LUA (Collectibles.lua)
- [x] MOVE CYRODIIL/BATTLE SPIRIT TO SEPARATE LUA (Cyrodiil.lua)
- [x] MOVE DISGUISE/STEALTH TO SEPARATE LUA (Stealth.lua)
- [x] Check that BOUND AEGIS code still works
- [x] Cyrodiil Buffs - Streamline - have a single function handling both player/reticleover called when relevant
- [x] SCB Stealth Buff - Streamline, have 1 func for handling disguise state that accepts both player/reticleover input called from relevant categories.
- [x] SCB Disguise Buff - Streamline, 1 func for determining disguise, use handlers for basic code only so as to eliminate redundant code
- [x] SCB Collectible Buff - Streamline, check how AVA Status returns in BG and put better return statement when in AVA
- [x] Resolve any leftover localization TODOs, for example in SCB.AddToCustomList()

HOOKS:
- [x] GetKillingAttackerInfo = function(index) --> Add an addPlayer option to change the source for some player effects that shouldn't show as self sourced (Lava, Water in Maelstrom Arena 5, etc)

Check/Fix Death Recap Sources
- [x] Lava Id's
- [x] Fire Trap
- [x] Slaughterfish
- [x] VMA Water
- [x] DSA Hazards (if any)

**Comment by psypanda** [comment]
Marked localization TODO as done since bad2730b376213af10aea58a4f06a1c7d5b2c986 resolved that.
