### ISSUE TITLE
Summon Cat Banker Keybind

### ISSUE THREAD

**Issue by summerz05** [DakJaniels/LuiExtended#129]
Current keybind only allows for Tythis Andromo the Banker to be summoned on keybind 

Please add the new Cat Banker to be keybound.

Thank you

**Comment by ArtOfShred** [comment]
Implemented on GitHub build (WIP):

TODO:
- [x] Menu option string localization
- [x] New icons for SCB component for the cat banker/merchant
- [x] Keybind setup (Separate for each type of banker)
- [x] Add "Cannot use in Imperial City" message [TEST ON LIVE]
- [x] Add summoned/unsummoned message (probably need event handler for this in CA)
- [x] Move handler for summoned/unsummoned message to CA

**Add menu options for Collectible Summon notifications to CA**
- [x] Toggle notification on/off for each Assistant/Vanity/Memento
- [x] Display CA / Display Alert (Note CA for /commands = ALWAYS, toggle should be for ANY memento use to trigger this)
- [x] Pet Nickname - Yes or No toggle
- [x] Icon - Yes or No toggle
- [x] Choose bracket link style
- [x] Choose line font color

**Comment by ArtOfShred** [comment]
All implementation complete!
