### ISSUE TITLE
Horizontal Prominent (De)Buffs

### ISSUE THREAD

**Issue by Cheunn-Panaa** [DakJaniels/LuiExtended#137]
**Is your feature request related to a problem? Please describe.**
Buff tracking displays way to much buffs for me, blacklist would take a huge amount of time, so i'm using the prominent Buff and Debuff containers. But you can only display it in a vertical way which is for my ui not appropriate.

**Describe the solution you'd like**
Adding a posibility to display it horizontally with a checkbox in the prominent buffs/debuffs panel.

**Describe alternatives you've considered**
An alternative would be to whitelist buffs instead of blacklisting it which would lead to a useless prominent buff/debuff container ?

**Additional context**
.
![unknown](https://user-images.githubusercontent.com/22621989/66717206-ac3d6600-edd6-11e9-8fe9-a423181c798e.png)

I might try to do a pullrequest to this when i've got some free time

**Comment by ArtOfShred** [comment]
Implemented for update 5.9.5.
