### ISSUE TITLE
About "player name display method(player/target)"

### ISSUE THREAD

**Issue by NStunner** [DakJaniels/LuiExtended#140]
I like to see character name with @accountname on my unit frame bar. But some names or account names are so long. I've set the bars long, still not enough. My suggestion is that we can set the character name and account name, one at the bottom and the other at the top.

**Comment by ArtOfShred** [comment]
I don't have any intention of coding a bottom wraparound for names at the moment. Maybe in the future if I significantly rewrite Unit Frames to make elements around the frame modular.
