### ISSUE TITLE
Adding vAS minibosses Health

### ISSUE THREAD

**Issue by Cheunn-Panaa** [DakJaniels/LuiExtended#143]
**Is your feature request related to a problem? Please describe.**
Base game do not show vAS mini bosses life while doing the hard mode. (same for vCR).
In some encounters like vMOL and vHOF game displays all bosses health.

**Describe the solution you'd like**
In vAS / vCR, when hardmode is enabled, display mini-bosses HP in an additionnal frame.

**Describe alternatives you've considered**
.

**Additional context**
vAS id : 1000
Llothis id:47106
Felms id: 55923

**Comment by ArtOfShred** [comment]
Unfortunately if the game doesn't display a unitFrame for the bosses, I'm unable to create one.
The most I'd possibly be able to do is like, create a frame that updates when you targeted/damaged each individual boss with their current HP snapshotted but it wouldn't be dynamic unless you were dealing damage to them and the backend for that would be a bit excessive.

This would be a good request to make to ZOS to actually show them as eligible boss unit tags.
