### ISSUE TITLE
More Horizontal Alignment Method Controls

### ISSUE THREAD

**Issue by JoshStrobl** [DakJaniels/LuiExtended#144]
**Use case**

I'm wanting to horizontal align player (self) buffs to the right and put them up in the top right of my UX next to my compass / map, while maintaining left-aligned debuffs for player (self) +target and left-aligned buffs on target.

Right-aligned player buffs:

![right-aligned-buffs](https://user-images.githubusercontent.com/156574/72680156-4d674700-3abf-11ea-9646-be63bbfe9a91.JPG)

Right-aligned target debuffs that I'd love to be left-aligned:

![debuffs-left](https://user-images.githubusercontent.com/156574/72680172-a8993980-3abf-11ea-89b3-ff73586513be.JPG)

Right-aligned player debuffs (location, player has no debuffs at time of posting) that I'd love to be left-aligned:

![player-debuffs](https://user-images.githubusercontent.com/156574/72680257-658b9600-3ac0-11ea-8bcf-f3992bdd1747.JPG)

**Describe the solution you'd like**

I'd like controls for the following:

- Horizontal Alignment Method (Player - Long Term Buffs)
- Horizontal Alignment Method (Player - Short Term Buffs)
- Horizontal Alignment Method (Player - Short Term Debuffs)
- Horizontal Alignment Method (Target - Buffs)
- Horizontal Alignment Method (Target - Debuffs)

**Describe alternatives you've considered**

I haven't considered any other alternatives because LUI Extended is the only competent UX customization add-on that I've encountered in ESO.

**Comment by ArtOfShred** [comment]
I'll try to look into this after I get the update out for Harrowstorm. I'm thinking of doing a bit of a rewrite to try to optimize the sorting code, and maybe allow different sorting/alignment methods for each individual container.

**Comment by ArtOfShred** [comment]
Made a tracker for Buffs & Debuffs changes here and added this into it: https://github.com/ArtOfShred/LuiExtended/issues/179

Closing this issue.
