### ISSUE TITLE
[Request] Show Stamina % on Health Labels

### ISSUE THREAD

**Issue by Imiona** [DakJaniels/LuiExtended#149]
Hello

I would like to make a suggestion regarding Label Formats.

Is it possible to add Magika/Stamina percentages to the Label Formats. Right now, only Health and Shield related Options are Possible.

![stam](https://user-images.githubusercontent.com/11210717/74760099-33fe1a00-527a-11ea-8a13-37abde474fd9.png)

What i would like to show is:

+Stamina and/or Magika Percent

so i can still see my Stamina even the Stamina/Magika Labels are turned off.

thx

**Comment by Imiona** [comment]
Edit:

Could you add an Option to merge Player Buffs with the Long Term Effects Buffs Bar?

**Comment by ArtOfShred** [comment]
I'm not really super inclined to do this as I'd have to register more handlers to that bar to update those values all the time and I feel like in most cases it would be too busy.

For the second suggestion, I'd try just turning off Long Term Effects so all the buffs are in one frame together. I'll probably be looking into adding some more organization options for buffs in the future.

**Comment by Imiona** [comment]
Thx for the Info Art, i managed to find the option for the Buffs :)
