### ISSUE TITLE
Activity Finder status window

### ISSUE THREAD

**Issue by Xinayder** [DakJaniels/LuiExtended#156]
**Is your feature request related to a problem? Please describe.**
The activity finder UI component has its position and contents hardcoded. I use a minimap addon and I can barely notice my queue status because the window is on top of my minimap (using a different addon).

**Describe the solution you'd like**
Not sure if it's possible but I'd like to suggest being able to theme and reorganize the activity finder status window.

**Describe alternatives you've considered**
I can install another addon to move this component elsewhere, but it would be nice to be able to style the UI component 

**Additional context**
![](https://cdn.discordapp.com/attachments/408739478044278805/706275935053152366/unknown.png)

**Comment by ArtOfShred** [comment]
Yeah I'm in the same boat actually, using Azurah to move this and the quest tracker and timer down for the time being.

I'll jot down that I really need to at LEAST add an unlock for these couple of UI elements.

**Comment by ArtOfShred** [comment]
Implemented on development build. Will do a new release relatively soon.
