### ISSUE TITLE
Pet names localization

### ISSUE THREAD

**Issue by FAR747** [DakJaniels/LuiExtended#165]
Are there plans to add pet names to the Pet Frames in the localization?

If all the same there are plans, then I ask you to immediately add the ability to assign a pet several names for compatibility with double name add-ons.

(One addon is still popular among the RU community. It allows you to display a double name (RU + ENG or ENG + RU). Example in the screenshots below)
![eso64_2020-06-30_16-46-32](https://user-images.githubusercontent.com/17673310/86133703-5853e800-baf1-11ea-8581-6b54f4aba97f.png)
![eso64_2020-06-30_16-46-10](https://user-images.githubusercontent.com/17673310/86133715-5db13280-baf1-11ea-991a-b2de195b7689.png)

**Comment by ArtOfShred** [comment]
Pushed an update to GitHub, I converted the pet names to strings in .en/ru/de.lua files for localization.

As far as the double name addon, what is it called? I'm not sure what method they use to change the pet names so it might work fine with just normal ru pet strings added (Also I can probably get the ru pet name strings from that too maybe).

**Comment by FAR747** [comment]
The addon is called RuESO. I checked on the current version from ESOUI and adding the name RU + ENG works. (I added the name manually through the settings. The last option in the screenshot).
![изображение](https://user-images.githubusercontent.com/17673310/86309552-b2a19580-bc24-11ea-8bed-65b7396722fd.png)

About RuESO. As I understand it, he simply adds up the Russian name and the English name enclosing it in brackets. (It depends on the settings)

**Comment by ArtOfShred** [comment]
Hmm, and when you use just the Russian name in the whitelist it doesn't show the pet unit frame at all then?

I guess he must hook GetUnitName("unitTag") or something so the value returns differently. I'll take a look tomorrow, been spending my early day working on LUIE and the rest of the night pvping :-P

**Comment by FAR747** [comment]
I tried to add only in Russian and it did not work.

There is an idea to add a button to the settings which, when clicked, add all summoned pets to the white list. This may partially solve the problem.

**Comment by ArtOfShred** [comment]
Ooh yeah that's a great idea to just add the current pet frame names in. Otherwise I'd have to somehow store the strings for all the en/ru pet names and like...
hmm...
yeah I'm not even sure lol. It'd be really difficult to add direct support for this without literally storing all the possible strings like "en name (ru name)", "ru name (en name)" etc and I'd prefer not to add that many extra strings.

I'll maybe see about adding a button that iterates through your active pets and adds them to the list in a bit here.

**Comment by FAR747** [comment]
Good.

I will soon translate the names of pets in ru.lua

**Comment by ArtOfShred** [comment]
Alright that ended up working pretty well. Pushed a commit on the master branch.

**Comment by FAR747** [comment]
Checked. The add pet button works well.

**Comment by ArtOfShred** [comment]
Awesome.

Gonna go ahead and close up this issue for now. If you think of anything else feel free to toss up a new issue.
