### ISSUE TITLE
Objective Capture Meter

### ISSUE THREAD

**Issue by dndrmm** [DakJaniels/LuiExtended#166]
**Describe the bug**
In Cyrodiil, when capturing a resource the objective capture meter outline and fill appear offset from each other. 

**To Reproduce**
Go to Cyrodiil and attempt to capture a resource.
The meter appears as shown in the screenshot.
In this screenshot, the meter has been moved from the default location (not clear if that is the cause).

**Expected behavior**
The outline and fill should be in the same location.

**Lua Error**

**Screenshots**
![luie_bugreport_objectivemeter](https://user-images.githubusercontent.com/62021841/86148948-4c543000-bac9-11ea-9809-dcd0589fb982.png)

**Other installed AddOns**
In order to test his bug, I have disabled all other addons, and restarted the client. In the screenshot LuiExentended is the only addon running.

**Comment by ArtOfShred** [comment]
Ah that's interesting, not sure why the fill isn't aligned to the parent. I should be able to reanchor it specifically when it's moved, taking a look.

**Comment by ArtOfShred** [comment]
Alright, fixed on the GitHub build. I might try to do an update within a couple days here or so.
