### ISSUE TITLE
Interrupt Alert Not Appearing

### ISSUE THREAD

**Issue by Niobiritzu** [DakJaniels/LuiExtended#168]
**Describe the bug**
The Interrupt alert does not appear in the action area.

**To Reproduce**
Steps to reproduce the behavior (please be as specific as possible):
1. Fight any mob that has an interruptable ability.
The example I have been using is the Nix-Hound with it's Leech ability.

**Expected behavior**
The option to "Interrupt" should appear but does not.

**Lua Error**
No error (or I don't know how to find it)

**Screenshots**
When I changed the tag to "Avoid" as true here then we see the expected result.
![image](https://user-images.githubusercontent.com/15780681/86499767-f0083f00-bd5a-11ea-924c-b856c21a294c.png)

However, when we have the standard "Interrupt" there is no alert.
![image](https://user-images.githubusercontent.com/15780681/86499840-3c537f00-bd5b-11ea-9b9f-3398558476b0.png)

**Other installed AddOns**
AlphaGear 2
Combat Metrics
HarvestMap
LoreBooks
MiniMap
QuestMap
SkyShards

I am looking through the code but I'm not familiar enough with the calls to see the issue yet. I will keep looking and if I find the answer, then I will post a follow up with what I did to fix.

Thanks for the great addon!

**Comment by Niobiritzu** [comment]
An update to the post. I changed the tag to "shouldusecc = true".
![image](https://user-images.githubusercontent.com/15780681/86501330-f18b3480-bd65-11ea-8646-61755a0dbc0e.png)

Then I got an expected result. It seems to be evaluating the "interrupt" variable as false regardless of what is set.

![image](https://user-images.githubusercontent.com/15780681/86501326-e932f980-bd65-11ea-8f2c-956404f58db2.png)

**Comment by Niobiritzu** [comment]
Okay, I figured out what was happening.
![image](https://user-images.githubusercontent.com/15780681/86502098-7ded2580-bd6d-11ea-8d14-2a6d3282a7bf.png)
The variable "stringInterrupt" was being overridden by the "shouldusecc" if statement.

I added a string called "stringShouldCC" to prevent the overriding of values for "stringInterrupt".
![image](https://user-images.githubusercontent.com/15780681/86502095-6c0b8280-bd6d-11ea-8a3a-c2412ecf5611.png)

I am attaching the updated LUA if you feel it is completed.

Thanks again for the great add on. I really enjoy it.


Here is the confirmation that it is now working as intended.
![image](https://user-images.githubusercontent.com/15780681/86502179-53e83300-bd6e-11ea-9414-b79e2dd8fc57.png)



[AbilityAlerts.zip](https://github.com/ArtOfShred/LuiExtended/files/4871932/AbilityAlerts.zip)

**Comment by ArtOfShred** [comment]
![G3D7i](https://user-images.githubusercontent.com/22554243/86519412-93635d80-be08-11ea-8b35-5b3c4d8e52ed.png)
Wow what a silly oversight on my part. Thanks for taking the time to dig into this for me!

The idea with the hard cc string replacing the interrupt string is you'd never need both so it displays as either one or the other, so I'm just gonna use an if/elseif/else statement to fix it.

**Comment by Niobiritzu** [comment]
Yes, this makes more sense. I didn't have a hard cc mob to test on so it would have been a while before I noticed both popping up XD.
Either way, appreciate the addon as it is very very good since I'm playing a tanking role. I'm just glad I could be useful!
