### ISSUE TITLE
Make the ultimate percentage cap optional

### ISSUE THREAD

**Issue by Alhelor** [DakJaniels/LuiExtended#181]
At some point a cap to the ultimate percentage has been implemented (if>100 -> 100). I never understood the point of it, as it was always possible to make the number disappear in settings once ulti reached 100. However, knowing "how many times your ultimate" you have can be very useful for certain setups where having twice or three times the ultimate points needed changes its function.

Thus, though I really love this addon, it is very annoying for me to go into the files and remove that line of code every time there's an update. Please add a setting that will make this cap optional.

Thank you!

**Comment by ArtOfShred** [comment]
I considered doing this at some point, it's easy enough so I'll add it to the todo list.

Closing this since I added the issue into #148
