### ISSUE TITLE
Compact mode for Group frame

### ISSUE THREAD

**Issue by McAkudza** [DakJaniels/LuiExtended#185]
I'm always frustrated when i see this group frame that has lot of empty space beteween health bars, it just looks not systematized with other interface pieces or add-ons like "hodor reflexes"

I want to see a compact mode for it, like in BUI or like in LUI but in raid group frame

For example in BUI there is a checkbox in settings that can turn on compact mode

![image_2020-11-03_190535](https://user-images.githubusercontent.com/9479198/97983229-8e8ad680-1e07-11eb-9a3a-d2d9da1943aa.png)
this is how my interface looks like now
![image_2020-11-03_190620](https://user-images.githubusercontent.com/9479198/97983289-a95d4b00-1e07-11eb-8b07-930102b79663.png)
and here is an example with BUI, where u can see a compact moded group frame, and it looks really simple and neat

**Comment by ArtOfShred** [comment]
Only thing I can suggest for now is to disable Custom Group Frames (leave Custom Raid Frames on) and the addon will use the Custom Raid Frames for 4-man groups as well.

This would be a fairly big undertaking to write separate control code for having a compact frame layout. But it's something I might consider in the future if I'm spending more development time on LUIE. Thanks for making the suggestion!

**Comment by ArtOfShred** [comment]
Gonna close this one out since the raid frames effectively accomplish this (and the raid frames can be used in lieu of the group frames in the options).
