### ISSUE TITLE
Text error in menu: "Target - Transparency - Out-of-Combat"

### ISSUE THREAD

**Issue by luke4mls** [DakJaniels/LuiExtended#186]
The menu option for setting target unit frame transparency in-combat is incorrectly title as "Out-of-Combat". The tooltip text is correct.

Unit Frames > Custom Unit Frames (Player & Target) > Target - Transparency

![image](https://user-images.githubusercontent.com/3845336/99196377-9f194600-2751-11eb-85bb-c924db3ba2a5.png)
![image](https://user-images.githubusercontent.com/3845336/99196394-b7896080-2751-11eb-8cca-757df2ac6623.png)

**Comment by luke4mls** [comment]
solution:
settings/UnitFrames.lua line 953
```
- name = GetString(SI_LUIE_LAM_UF_CFRAMESPT_TARGET_OOCPACITY),
+ name = GetString(SI_LUIE_LAM_UF_CFRAMESPT_TARGET_ICPACITY),
```

**Comment by ArtOfShred** [comment]
Thanks for reporting this, fixed on GitHub build.
