### ISSUE TITLE
"Long Term Player Buffs" stuck on centered alignment while in horizontal orientation

### ISSUE THREAD

**Issue by luke4mls** [DakJaniels/LuiExtended#187]
The icons are also not centered within buff window. They appear to have their baseline in the center of the box.

![image](https://user-images.githubusercontent.com/3845336/99196468-2ebef480-2752-11eb-8339-b4fd9242adcd.png)
![image](https://user-images.githubusercontent.com/3845336/99196479-3aaab680-2752-11eb-9690-20db4ec345cb.png)

**Comment by ArtOfShred** [comment]
Fixed on the GitHub build, thanks for reporting this and providing a solution!
