### ISSUE TITLE
Unit Frames > Raid Spacers

### ISSUE THREAD

**Issue by luke4mls** [DakJaniels/LuiExtended#188]
Updating any value in the Unit Frames settings reverts the "Add Spacer for Every 4 Members" setting to "OFF"

**Comment by luke4mls** [comment]
Solution:
LuiExtended/settings/UnitFrames.lua     line 1656 missing the word "value"

```
- setFunc = function(value) Settings.RaidSpacers = UnitFrames.CustomFramesApplyLayoutRaid(true) end,
+ setFunc = function(value) Settings.RaidSpacers = value UnitFrames.CustomFramesApplyLayoutRaid(true) end,
```

**Comment by ArtOfShred** [comment]
Fixed on GitHub build, thanks for reporting and providing a solution!
