### ISSUE TITLE
Combat info module : ^f and ^m tags.

### ISSUE THREAD

**Issue by Lenitsag** [DakJaniels/LuiExtended#189]
**Describe the bug**
I saw in your changelog that you might have worded on a similar issue in version 6.0.8, but I still see ^f tags after a skill that i'm suppose to block or avoid. I'm using the french client. 

**To Reproduce**
1. Went to a random zombi with my french client
2. Waited he trigger the combat alert 

**Screenshots**
![image](https://user-images.githubusercontent.com/25960445/102800891-d0221180-43b4-11eb-8ad5-537b0233da4b.png)
![image](https://user-images.githubusercontent.com/25960445/102800956-e4fea500-43b4-11eb-8bfe-8d2fd3753941.png)

**Other installed AddOns**
Not much, except BanditUI because I also like some of their stuff;
I also reproduce this bug without banditUI, I can test without any other addon if you need !

**Comment by ArtOfShred** [comment]
Thanks for reporting this, I'll have to figure out where I missed formatting the strings for the ability name here.

**Comment by ArtOfShred** [comment]
Alright, found the issue and fixed it on the GitHub build. Thanks for reporting! This will be worked into whenever the next release is.
