### ISSUE TITLE
UI Error in combat casting Shimmering shield

### ISSUE THREAD

**Issue by andrewspiers** [DakJaniels/LuiExtended#196]
**Describe the bug**
UI Error in combat casting Shimmering shield.

**To Reproduce**
Steps to reproduce the behavior (please be as specific as possible):
1. Enter combat
2. Cast shimmering shield

**Expected behavior**
No UI Error

**Lua Error**
user:/AddOns/LuiExtended/modules/SpellCastBuffs/SpellCastBuffs.lua:2408: attempt to index a nil value
stack traceback:
user:/AddOns/LuiExtended/modules/SpellCastBuffs/SpellCastBuffs.lua:2408: in function 'SpellCastBuffs.OnCombatEventIn'
|caaaaaa<Locals> eventCode = 131106, result = 2460, isError = F, abilityName = "Shimmering Shield", abilityGraphic = 25711, abilityActionSlotType = 0, sourceName = "Skeletal Marksman", sourceType = 0, targetName = "walks-into-stuff^Mx", targetType = 1, hitValue = 927, powerType = -1, damageType = 1, log = T, sourceUnitId = 55282, targetUnitId = 43964, abilityId = 92170 </Locals>|r

**Screenshots**
![image](https://user-images.githubusercontent.com/170054/114250629-7f730a80-99dd-11eb-90fd-3dd69f4bfb31.png)

**Other installed AddOns**

ActionDurationReminder
AlphaGear
AsylumTracker
AwesomeGuildStore
CombatAlerts
CombatMetrics
CombatMetronome
CraftStoreFixedAndImproved
displayleads
DolgubonsLazyWritCreator
EssentialHousingTools
History
HodorReflexes
IIfA
libAddonKeybinds
LibAddonMenu-2.0
LibAlchemyStation
LibAsync
LibBinaryEncode
libChat2
LibChatMessage
LibCombat
libCommonInventoryFilters
LibCustomMenu
LibDateTime
LibDebugLogger
LibFeedback
LibGPS
LibLazyCrafting
LibMainMenu
LibMainMenu-2.0
LibMapPing
LibMediaProvider-1.0
LibPhinixFunctions
LibPromises
LibRunebox
LibSlashCommander
LibStub
LibTableFunctions-1.0
LibTextDict
LibTextFilter
LightAttackHelper
LovelyEmotes
MapPins
MasterMerchant
MasterRecipeList
MiniMap
MM00Data
MM01Data
MM02Data
MM03Data
MM04Data
MM05Data
MM06Data
MM07Data
MM08Data
MM09Data
MM10Data
MM11Data
MM12Data
MM13Data
MM14Data
MM15Data
MM16Data
MultiCraft
pChat
PetDismiss
PocketAdeptus
PortToFriendsHouse
PotionMaker
PurgeTracker
RaidNotifier
ShoppingList
Siroria
SuperStar
TamrielTradeCentre
TraitBuddy
UCT
USPF
VotansFishFillet

Note: the error above was from this commit: 863db0e65a17f5c6eddbc7d7f8cec2a205e628db, but also occurred on v6.2.5

Thanks for maintaining this lovely addon!

**Comment by ArtOfShred** [comment]
Thanks for posting! Just took a look and found what I believe is the problem. Pushed a commit, I probably won't get around to testing anything until tomorrow, but I'll take a look then.

**Comment by ArtOfShred** [comment]
Tested and pushed a new commit e98a81f32c5203c5c904c88208243dc7b5fc8ee8. Issue should be resolved.

**Comment by davebirch** [comment]
Just came to report this one, glad to hear it's already fixed :D
