### ISSUE TITLE
Can't turn on cooldown tracker for skillbar

### ISSUE THREAD

**Issue by pikaliov** [DakJaniels/LuiExtended#209]
hello, have not a cooldown on ability ,i dont know why, have just a green highlight, can u help me pls??
Can't turn functional to see CD on skillbar, it says 'BROKEN'. I use standart add-ons for raid, nothing special (Hodor Reflexes, Raid Notifier, Combat Alerts, Player Role Indicator, Autorecharge).
I see in issue section u mark this issue. Any progress?

**Comment by ArtOfShred** [comment]
I mentioned this in the patch notes for the update. This component is currently broken with the release of Blackwood. I spent a long time trying to figure out what was wrong but didn't have any luck. It's something I'll revisit in the future when I have more time/patience - might have to rewrite the entire component.

**Comment by pikaliov** [comment]
Okay, thanks for answer anyway.

**Comment by flatline-studios** [comment]
Have you considered \*ahem\* _borrowing_ from another addon that this functionality works with?

I love this addon, but this feature being broken is a real drag... I'm not very familiar with LUA, but I'd happy to try and help fix this, if you can point me to the file/core function(s) that's responsible for this functionality. :)

**Comment by ArtOfShred** [comment]
Closing this issue finally since DakJaniels found the solution!
