### ISSUE TITLE
Add more combat notifications for dingeon

### ISSUE THREAD

**Issue by pikaliov** [DakJaniels/LuiExtended#210]
Hi. Today I tried LUI, the problem is in the dungeons this add-on didn't popup notifications for aoe, heavy attacks. For example in Fungalo Grotto 1, on the 1st boss didn't announce heavy attack, on the last didn't announce heavy attack and aoe. Is there a problem with add-on or this announcements doesn't implement yet?

**Comment by ArtOfShred** [comment]
Yeah, everything has to be added manually and there are quite a few dungeons I haven't done, pretty much all DLC dungeons aren't done. If I get back into development more I'll probably get around to it eventually but, this might be a ways out at this rate.
