### ISSUE TITLE
Wrong unix permissions in release zip

### ISSUE THREAD

**Issue by Trojan295** [DakJaniels/LuiExtended#214]
**Describe the bug**

The release zip package contains files with read-only unix permissions, which makes it impossible to remove the extracted directory, without changing permissions/using root.

```bash
❯ ls -l LuiExtended/media/icons
total 116
dr-xr-xr-x 2 damian damian 114688 Jun  5  2021 abilities
```

One of the users of my addon manager spotted this issue:
https://github.com/Trojan295/eso-addons/issues/23

**To Reproduce**
Steps to reproduce the behavior (please be as specific as possible):

I believe this happens only on Linux (maybe also OSX) as it's connected with unix permissions.

 ```bash
 wget https://github.com/ArtOfShred/LuiExtended/releases/download/6.2.9/LuiExtended-6.2.9.zip
 unzip LuiExtended-6.2.9.zip
 rm -rf LuiExtended
 ```

results in multiple permission errors:
```
rm: cannot remove 'LuiExtended/media/icons/abilities/ability_spell_ranged_shock.dds': Permission denied
rm: cannot remove 'LuiExtended/media/icons/abilities/ability_set_crimson_twilight.dds': Permission denied
rm: cannot remove 'LuiExtended/media/icons/abilities/ability_summon_beast_lioness.dds': Permission denied
rm: cannot remove 'LuiExtended/media/icons/abilities/ability_set_kagrenacs_hope.dds': Permission denied
rm: cannot remove 'LuiExtended/media/icons/abilities/ability_spell_convalescence.dds': Permission denied
```

**Expected behavior**

Files in the zip should have also write permissions, so it's possible to remove them. `rm -rf LuiExtended` should remove the directory.

**Lua Error**
N/A

**Screenshots**
N/A

**Other installed AddOns**
N/A

**Comment by ArtOfShred** [comment]
I'm centuries late on this but is there something I can do on Windows to potentially fix this issue?

**Comment by saenic** [comment]
He should probably check if it still occurs. I created the zips with Windows 11 and edited them with 7zip.

**Comment by ArtOfShred** [comment]
Closing this issue for now. Feel free to reopen a new issue if you encounter this error again.
