### ISSUE TITLE
UI Error in media/icons/abilities/ability_airtronach_empower_flame.dds

### ISSUE THREAD

**Issue by Waywyrd** [DakJaniels/LuiExtended#215]
Error while extracting. Error opening file /home/name/Downloads/ESO/Lui-Extended-6.2.9/LuiExtended/media/icons/abilities/ability_airtronach_empower_flame.dds"

Because of this, it doesn't register the addon in the addons menu. Unsure if it's a thing with my computer(as I'm using linux if it's of any relevance) or the method of compression. By extracting normally this issue occurs. If you open the archive and extract everything manually it works fine.

Ingame UI error says this:

```
user:/AddOns/LuiExtended-6.2.9/LuiExtended/Initialize.lua:95: attempt to index a nil value
stack traceback:
user:/AddOns/LuiExtended-6.2.9/LuiExtended/Initialize.lua:95: in function 'OnAddonOnLoaded'
<Locals> eventCode = 65536, addonName = "LuiExtended" </Locals>
```

Other addons I use:

Action Duration Reminder
Auto Recharge
AwesomeGuildStore
Bag Space Indicator
Code's Combat Alerts
Dolgubons Lazy Writ Creator
Dustman
Lorebooks
Map Pins
Mass Deconstructor
Personal Assistant
Qcell's Rockgrove Helper
Resource Radar
SetCollectionMarker
The Tamriel Mapping Project
Votan's Rune Tooltips

**Comment by ArtOfShred** [comment]
Way behind on this but do you know if there is anything I can potentially do in Windows to fix this issue? I'm not sure why there would be a problem with some files here.

**Comment by ArtOfShred** [comment]
Closing this issue for now. Feel free to reopen a new issue if you encounter this error again.
