### ISSUE TITLE
Sort buffs list in grid instead long vertical list with pyramid resource bars

### ISSUE THREAD

**Issue by barfabi1** [DakJaniels/LuiExtended#225]
I'd like option to unlock buffs/debuffs list from custom unit frame but keep option to sort buffs in grid XY view instead of endless horizontal list when player frames are set pyramid or horizontal.

Current view when play custom frames are set as pyramid with unlocked buff list on different position causes showing up all buffs in one line. With defaul stacked horizontal frames all buff list is contained in grid view and screen is less polluted.

Below current settings and proposal of solution.

![before](https://github.com/ArtOfShred/LuiExtended/assets/11408887/39f54a1b-5a67-4024-9878-011477d75f84)
![after](https://github.com/ArtOfShred/LuiExtended/assets/11408887/ef44926e-f289-410a-9409-bf5dca9235cb)

**Comment by ArtOfShred** [comment]
Just updated on GitHub with this functionality. You can customize the width of the Buff / Debuff fields individually for Player/Target and Buff/Debuff. You can customize whether the rows stack down or up as well.

Hopefully should be working pretty well with no issues. I've got a little bit of menu cleanup to do but outside of that seems to be working well.

**Comment by ArtOfShred** [comment]
Gonna close this issue for now since it's implemented. If you have any more feedback or suggestions, drop a thread over on the discussions: https://github.com/ArtOfShred/LuiExtended/discussions

**Comment by barfabi1** [comment]
Thank you so much! 
Where can I activate this setting? 
![anchor](https://github.com/ArtOfShred/LuiExtended/assets/11408887/0ee1e19f-57c4-4bdc-8b62-d196cb0b2d04)

**Comment by ArtOfShred** [comment]
Oh it's right at the top of the UnitFrames menu before any of the submenus. "Hard-Lock Position to Unit Frames"

(Sorry for the slow response didn't check my email for a couple days)

**Comment by barfabi1** [comment]
It's looking fantastic! Great work and so much better optimisation! Wishing you all the best :)
![lui](https://github.com/ArtOfShred/LuiExtended/assets/11408887/be9c74a4-e3c2-41ce-8b07-3128b062c118)
