### ISSUE TITLE
ability proc sound broken

### ISSUE THREAD

**Issue by necco889** [DakJaniels/LuiExtended#228]
Hey, the sound notification on ability procs are not playing like crystal frags, etc
The reason is this change, the global variable got a local qualifier between 6.5.0 and 6.5.1 for some reason

https://github.com/ArtOfShred/LuiExtended/blame/c39733398218bd041e19a47900f28d645d5c026a/modules/CombatInfo/CombatInfo.lua#L1187

**Comment by DakJaniels** [comment]
I have this fixed in my brach. Working on some other changes before sending in the pull request though. Feel free to use mine in the interim.

**Comment by necco889** [comment]
tested on the master branch and it works again thx!
