### ISSUE TITLE
Experience Announcements can't be disabled.

### ISSUE THREAD

**Issue by gurkoz** [DakJaniels/LuiExtended#24]
Seems like it's impossible to disable announcements of XP in the chat. I have tried a number of variations but something seems broken with this feature. Even when set to off a string is shown telling me current xp and gain towards the next level.

Other than this, frikkin' awesome addon! I can't live without it! Keep up the great work!

I am using Beta v4.99.

**Comment by ArtOfShred** [comment]
Yeah its broken in the current GitHub release. Just need to remove one line
to fix it lol. I'll try to get that corrected later today, sorry about
that. Usually try to clean up sloppy leftovers before I upload to GitHub
but I left that one in accidentally.
Thanks for your feedback!

**Comment by gurkoz** [comment]
Awesome lightning fast reply! In otherwise a perfect addon this was just a small thing i noticed. Glad to hear it will be fixed in future versions ;)

Sorry for my lacking GitHub knowledge but is there anywhere to make suggestions for features to add? Should those be added under "issues" in any particular fashion?

Thanks again for all your time and effort spent building and managing a mod like this.

**Comment by ArtOfShred** [comment]
Hmm, the best place to submit feedback for features to add would be to send me a PM over at ESOUI or post on the comment thread: http://www.esoui.com/downloads/fileinfo.php?id=818#comments. 

Anything you post there I can pop over into my feedback/idea list I have sitting around locally. You can also email me directly at artofshred@artofshred.net too!
