### ISSUE TITLE
Large Group message showing with CA Module disabled.

### ISSUE THREAD

**Issue by Medicate117** [DakJaniels/LuiExtended#249]
**Describe the bug**
When Chat Announcement Module is disabled it shows "Your Group is now a large group" whenever i join or change zones.
When CA Module is active and option is deactivated, it works fine. Took me a week to figure out, which addon and why it does so.
I mean sure, now that i have disabled every single option in CA module, i could leave it active, but i think this is not how it's intended,
Didn't notice any other message from CA module bugging thru.

**To Reproduce**
Steps to reproduce the behavior (please be as specific as possible):
1. Install LUI
2. Deactivate Chat Announcement Module
3. Join a large Group with over four Members
4. Get the Chat Message "Your Group is now a large group" and every time you change zone, it writes it again.

**Expected behavior**
When CA Module is "Off", all functions should be off.

**Lua Error**
`Copy and paste the Lua Error message here.`

**Screenshots**

**Other installed AddOns**
Reall all? okay.
BSC-Advanced Synergies
Combat Metrics
Combat Metronome
Crutch Alerts
ExoYs Proc Set Timer
Fancy Action Bar
Hodor Reflex
Inventory Insight
Loot Log
No, thank you!
OdySupportIcons
pChat
Raid Notifier
Wizard's Wardrobe
Libs not included

**Comment by ArtOfShred** [comment]
Thanks for the bug report. I'll look into what's causing this!

**Comment by ArtOfShred** [comment]
Alright figured out the issue. The dev branch is updated with this fix. Next release will have the fix (planning to release for the ESO update unless I run into any issues causing UI errors).

EDIT: Just to provide a little more detail - effectively some functions in Chat Announcements still run to interact with other modules even when CA is disabled - but this one shouldn't have been so I've excluded it from that now. Thanks for providing a bunch of detail in your bug report!

**Comment by Medicate117** [comment]
That was really fast. Thanks for the fix and reply. 
Great work, keep it up :)
P.S. Wasn't sure, how much details were needed. Noted if i have to report again.

**Comment by Medicate117** [comment]
That was really fast. Thanks for the fix and reply.
Great work, keep it up :)
P.S. Wasn't sure, how much details were needed. Noted if i have to report again.
