### ISSUE TITLE
Unit Frames - No colors.

### ISSUE THREAD

**Issue by Naladdar** [DakJaniels/LuiExtended#284]
I am probably a bit stupid, because is searched for this behavior and found nothing, so its probably pebcac.

**Describe the bug**
My unit frames have no colors, just the frames and the text.

**To Reproduce**
Deactive all addons, beside this one and the needed libs.

**Screenshots**
![image](https://github.com/ArtOfShred/LuiExtended/assets/10608926/2c8c1722-ef85-44b2-a6a6-3f5694531f9e)

**Other installed AddOns**
Node besides LUI and needed libs.

**Comment by saenic** [comment]
Your textures are missing. There is a note about this in the sticky comment on esoui.

**Comment by Naladdar** [comment]
Pebcac Issue -

**Comment by Naladdar** [comment]
So, it's still probably my fault, but it still dont show textures.
Deleted everything (SavedVariables/Addons), redownloaded LUI and libs, reinstalled them, reloaded TESO
Now i am really unsure what i am doing wrong.


![image](https://github.com/ArtOfShred/LuiExtended/assets/10608926/ff948b26-9192-4b3b-b3e5-b5b4a57472de)

![image](https://github.com/ArtOfShred/LuiExtended/assets/10608926/59f2dc89-0e91-4dea-aeb9-a5ea1d08df82)

![image](https://github.com/ArtOfShred/LuiExtended/assets/10608926/2a01f19e-cebe-4f41-b939-5ca001a166c2)

![image](https://github.com/ArtOfShred/LuiExtended/assets/10608926/37e86d26-cd08-402e-b2ca-c37cca62a509)

![image](https://github.com/ArtOfShred/LuiExtended/assets/10608926/90433d63-ceed-470e-8c53-2750d7e31748)

**Comment by DakJaniels** [comment]
Delete the ShaderCache in /Elder Scrolls Online/live while the game is completely closed. Relaunch the game the generate new texture paths.

**Comment by Naladdar** [comment]
> Delete the ShaderCache in /Elder Scrolls Online/live while the game is completely closed. Relaunch the game the generate new texture paths.

THAT did the trick! Thank you very much, it's so much better with colors ;-)

Could maybe be added to the sticky comment on esoui
