### ISSUE TITLE
New Assistant keybinds

### ISSUE THREAD

**Issue by Omenpapa** [DakJaniels/LuiExtended#287]
**Is your feature request related to a problem? Please describe.**
I cannot set the new assistans into LUI's keybinding. Ex.: We have a merchant, but that is only summoning the original one, instead of Fezez

**Describe the solution you'd like**
Add additional keybinds into the settings for each NPC
Ex.: 
Summon Merchant(Fezez)
Summon Merchant(Nuzhimeh)
Summon Bank(Tythis Andromo)
Summon Bank(Ezabi)

**Describe alternatives you've considered**
Alternative valid solution would be to somehow allow us to choose which NPC we prefer from a category. Ex.: We could choose Fezez and the current binding (Summon Merchant) would summon him.

**Additional context**
I own both Fezez and Nuzhimeh, and I would like to spawn Fezez only, since he is my preference.

**Comment by saenic** [comment]
This is already there albeit a bit hidden: At "Slash commands" -> "General" you can define which banker/merchant/assistant you summon when using the slash command or the keybinding. (the keybindings internally use the same function the slash command does).
I rewrote the script which scans your assistants and creates the dropdowns upon login/reload ui a year ago. If they do not work for you then please report back. I'm currently using Fezez and Ezabi without problems.

**Comment by Omenpapa** [comment]
> This is already there albeit a bit hidden: At "Slash commands" -> "General" you can define which banker/merchant/assistant you summon when using the slash command or the keybinding. (the keybindings internally use the same function the slash command does). I rewrote the script which scans your assistants and creates the dropdowns upon login/reload ui a year ago. If they do not work for you then please report back. I'm currently using Fezez and Ezabi without problems.

You are correct. I was not aware of this, actually the whole slash module was turned off. It does work as you described, thank you.
