### ISSUE TITLE
Add localization support

### ISSUE THREAD

**Issue by psypanda** [DakJaniels/LuiExtended#29]
It would be nice to have a proper localization of LUI somehow.

The esoui wiki provides a good read on that:
http://wiki.esoui.com/How_to_add_localization_support

We should also move from `string.format()` to `zo_strformat()` wherever localization is needed

Unique list of all ZOS strings: http://pastebin.com/pnFV3nKp (Warning: This is huge)

**References:**
- [localizegeneratedstrings.lua](https://github.com/esoui/esoui/blob/8f6f510cf06a67455d2f5ca0c07f15eeae602fe0/esoui/ingamelocalization/localizegeneratedstrings.lua)
- [localizeinternalingamegeneratedstrings.lua](https://github.com/esoui/esoui/blob/8f6f510cf06a67455d2f5ca0c07f15eeae602fe0/esoui/internalingamelocalization/localizeinternalingamegeneratedstrings.lua)
---

/root
---
- [x] `LuiExtended.lua`
- [x] `LuiExtendedMenu.lua`
  - [x] Info Panel Options
  - [x] Combat Info Options
  - [x] Buffs and Debuffs Options
  - [x] Chat Announcements Options
  - [x] UnitFrames Options
- [x] `LuiExtendedUI.lua`

/modules
---
- [x] `ChatAnnouncements.lua`
- [x] `CombatInfo.lua`
- [x] `InfoPanel.lua`
- [x] `SpellCastBuffs.lua`
- [x] `UnitFrames.lua`

/data
---
- [x] `Effects.lua`
- [x] `AbilityTables.lua`

**Comment by ArtOfShred** [comment]
Implemented!
