### ISSUE TITLE
Bugged Unit Frame Glow

### ISSUE THREAD

**Issue by bcrotty** [DakJaniels/LuiExtended#295]
**Describe the bug**
The player health bar and target health bar when the target is a player or companion have a shifting white glow in the background. It does not happen when the target is an NPC, pet, or familiar. I don't see a setting that affects this.

**To Reproduce**
Steps to reproduce the behavior (please be as specific as possible):
1. Load mod

**Expected behavior**
The glow seems like a bug that shouldn't be there.

**Lua Error**
None

**Screenshots**
![2024-06-08 16_17_52-Elder Scrolls Online](https://github.com/ArtOfShred/LuiExtended/assets/6155964/596c5b22-bb8c-45c9-a9a6-c83b1b11e523)

**Other installed AddOns**
The problem exists with just LuiExtended activated.

**Comment by DakJaniels** [comment]
Not a LUIE bug, Zos bug. It is in the update 42 know issue list. https://forums.elderscrollsonline.com/en/discussion/659638/pc-mac-update-42-known-issues#latest
