### ISSUE TITLE
LUI Buffs & Debuffs Bug with ESO Plus Symbol

### ISSUE THREAD

**Issue by ghost** [DakJaniels/LuiExtended#303]
I have the buffs and debuffs enabled with this addon and in the "long & short-term effect options" section, I have the "show ESO Plus Member On Player" option set to off, though the ESO Plus symbol is still visible on the permanent effects section of my screen as if the option is switched on. I tried to switch the option on and off and reloading my UI to see if that would fix the issue but to no avail.

Also, when I Disable the buffs and debuffs option entirely, the symbol disappears, so I doubt the issue involves other addons. It seems the setting itself is not working for me.

**Steps to reproduce the behavior (please be as specific as possible):**

1. Go to Settings
2. Click on "Addons" under the Settings **Dropdown Menu** (not the addons button that allows you to view, enable and disable all Installed addons)
3. Click on "LuiExtended - Buffs & Debuffs" 
4. Interact with "Long & Short-Term Effect Options"
5. Scroll Down to "Show ESO Plus Member On Player" option under the "Long-Term Effect Filters" Section

_What I expected to happen was for the ESO plus symbol indicator to disappear when I set the relevant option to off_

**Not sure what an LUA Error is**

Images:  https://imgur.com/a/ggDM0lj     **You may need to zoom in**

Image 1: Proof that the setting is turned off

Image 2: Symbol still on screen

### Addons I have Active:

Account Settings by Jodynn, Masteroshi430

Action Duration Reminder by Cloudor

Advanced Filters by Randactyl, Baertram

Auto Recharge by XanDDemoX, Baertram

AutoCategory by Shadowfen, crafty35a, RockingDice, etc.

AwesomeGuildStore by sirinsidiator

Azurah by Kith, Phinix, Garkin

BeamMeUp - Teleporter by DeadSoon, Gamer1986PAN

Code's Combat Alerts by code65536

CraftedPotions by Ayantir, sirinsidiator

CraftStore by AlphaLemming, BlackSwan, Rhyone... etc.

Crux Counter by g4rr3t

Daily Alchemy by Marify

Daily Provisioning by Marify

Display Leads by remosito

Dolgubon's Lazy Writ Creator by Dolgubon

Enchanted Quality by Rhyono, votan

Harvest Map by Shinni

Inventory Insight by manavortex, AssemblerManiac

Item Set Collection Tracker by Aleksandr Zelenin

Lockpick Notifier by Rednas

LoreBooks by Garkin, Ayantir, Kyoma, Sharlikran

Lost Treasure by CrazyDutchGuy, Scootworks, Gamer... etc.

Map Pins by Hoft, art1ink

Master Merchant by Sharlikran

PerfectPixel by KL1SK

PortToFriendsHouse by s0rdrak

Potion Maker by Facit, Khrill, votan

Quest Map by CaptainBlagBird, Sharlikran

Show TTC Price by VeronicaVyxie

Tamriel Trade Centre by TamrielTradeCentre.com

Urich's Skill Point Finder by Yachoor, tim99 etc.

Votan's Fisherman by votan

Votan's Fisherman Export by votan 

Votan's Minimap by votan

WritWorthy by ziggr

**Comment by DakJaniels** [comment]
This should be fixed for pc and gamepad interfaces.
