### ISSUE TITLE
grey UI color/boss bars coming up since update

### ISSUE THREAD

**Issue by Mireanthil** [DakJaniels/LuiExtended#307]
user:/AddOns/LuiExtended/modules/UnitFrames/UnitFrames.lua:3908: attempt to index a nil value
stack traceback:
user:/AddOns/LuiExtended/modules/UnitFrames/UnitFrames.lua:3908: in function 'UnitFrames.CustomFramesUnreferenceGroupControl'
user:/AddOns/LuiExtended/modules/UnitFrames/UnitFrames.lua:3831: in function 'UnitFrames.CustomFramesGroupUpdate'
user:/AddOns/LuiExtended/modules/UnitFrames/UnitFrames.lua:2092: in function 'InitializeCustomGroupFrames'
user:/AddOns/LuiExtended/modules/UnitFrames/UnitFrames.lua:2110: in function 'UnitFrames.OnPlayerActivated'

![image](https://github.com/user-attachments/assets/d5f242ba-9df3-4ae8-92bb-5fa376a794c3)

**Comment by Mireanthil** [comment]
![image](https://github.com/user-attachments/assets/54be2521-d922-4920-a02f-cd873ccf4d13)

**Comment by Mireanthil** [comment]
![image](https://github.com/user-attachments/assets/444d05e3-c4cb-4173-9524-c58c81277ea5)

**Comment by DakJaniels** [comment]
Thanks. I am looking into it. The main branch should be fine to use as those changes were reverted while I investigate why this happened.
