### ISSUE TITLE
Option to combine buffs and debuffs into single container

### ISSUE THREAD

**Issue by JohnPark234** [DakJaniels/LuiExtended#52]
Well it seems now days with so many addons having their own unique functions i noticed that my screen real-estate was losing room quick... as i moved components around to create the most efficient area, sneaking things in places and trying to play tetris with most of my addons on screen, i found that it would be awesome if there was some kind of option to combine buffs and debuffs for both target and player... since debuffs have a red outline and buffs have a green one i think it would be possible to differentiate between the two~ of course, if you guys want to that is... If its too much work Im still happy with using the Addon as is~

with much respect~

**Comment by ArtOfShred** [comment]
* [ ] Add menu option to set context filtering for all buffs & debuffs on player/reticleover to apply into container 1 only.

**Comment by ArtOfShred** [comment]
Closing this issue. Due to the already complex nature of sorting into multiple containers with prominent buffs & debuffs and fake auras I don't want to attempt this currently. May still decide to do something like this in the future.
