### ISSUE TITLE
[Feature Suggestion] Change Boss Bars Hight/Width

### ISSUE THREAD

**Issue by Imiona** [DakJaniels/LuiExtended#54]
Like the Title says, maybe you could add a option to change the hight/width of the Boss Bars.

And a few more suggestions that came up when i was playing/using Lui:

* Option to make Custom health/magicka and Stamina Bar Backgrounds
* Option to set the Colour of the Health Bars to Class Colours (if such thing even exists)
* Option to decrease the Magicka/Stamina Bar Hight lower than 20

Thx :)

**Comment by ArtOfShred** [comment]
Implemented!
