### ISSUE TITLE
[Feature Suggestion] Class Colors on Unit Frames

### ISSUE THREAD

**Issue by Arishem** [DakJaniels/LuiExtended#55]
Hi ArtOfShred,

Any way to add Class/Role Colors to the bar font?
That way the group/raid bars can stay red and the Role can be identified by the color of the player name.

Similar to what WoW allows: http://wowwiki.wikia.com/wiki/Class_colors

Thanks for the work on this awesome addon.

**Comment by ArtOfShred** [comment]
Implemented!
