### ISSUE TITLE
Bank interaction, "bad argument to string.format"

### ISSUE THREAD

**Issue by Kesmy** [DakJaniels/LuiExtended#58]
Infinite loop of these, when interacting with a bank. I don't know precisely what the problem is, but I know it must be related to the gamepad UI (or else the gamepad UI is just fast and this is a race condition), because I can't reproduce it otherwise...

Seems to do with putting items in the bank, switching to Withdraw to stack them, then switching back to Deposit and rapidly depositing another item... I really can't figure out exactly WHY it happens.

It might be a good idea to add a logPrefix == nil check to line 3371

2018-01-01T01:13:21.089-05:00 |cff0000Lua Error: bad argument #1 to 'string.format' (string expected, got nil)
stack traceback:
	[C]: in function 'string.format'
	user:/AddOns/LuiExtended/modules/ChatAnnouncements.lua:3395: in function 'CA.ResolveItemMessage'
	user:/AddOns/LuiExtended/modules/ChatAnnouncements.lua:9517: in function 'CA.PrintQueuedMessages'|r

**Comment by Kesmy** [comment]
Found it. Typo at

https://github.com/ArtOfShred/LuiExtended/blob/cbf64f1bb68cd335be8f47626863e23ae2af0f9a/modules/ChatAnnouncements.lua#L4059

Desposit => Deposit


I NEVER get notifications for stack changes, except this one...

**Comment by ArtOfShred** [comment]
Thanks! I'll check and fix it when I get off work tonight.
I'm not sure how I missed this one, unless its somehow specific to gamepad UI.

**Comment by Kesmy** [comment]
@ArtOfShred I'm almost certain that there's another bug here which is preventing notifications from bank actions,, but I can't figure out what it is.

I *ONLY* get notifications when depositing or withdrawing from a bank if I (in very rapid order, in the gamepad UI):

1) Deposit/Withdraw part of a stack of items
2) Deposit/Withdraw the second part of a stack
3) Press X,L3,X,A(,A) to Deposit/Withdraw another item. [that's switch/stack/switch/select(/confirm)]

Just withdrawing or depositing a single item, I never see anything. Maybe I don't have the right sequence of settings, but I only see one setting for bank withdrawals and deposits.

**Comment by ArtOfShred** [comment]
Okay I'll definitely take a look and see if I can replicate it. Last I checked the deposits/withdraws worked fine but I never checked on gamepad UI. 

Also is this for normal bank deposits or Guild banks? I'm not sure about gBank stuff because I don't have access to a guild bank on live or pts to check.

**Comment by Kesmy** [comment]
This is a normal bank (well, I'm using the assistant, which I think is a regular bank)

**Comment by ArtOfShred** [comment]
Yep assistant shouldn't be any different than normal bank. I'll look into everything as soon as I get home. Thanks for the details on how to try and replicate it!

**Comment by Kesmy** [comment]
It turns out to be BetterUI's ability to deposit and withdraw partial stacks that is causing the problem with bank notifications. I've been using it so long I forgot that's where the functionality came from.

You don't need to investigate it any further, just fixing the typo resolves the issue on your end.

**Comment by ArtOfShred** [comment]
Ooh okay got it. I might look into BetterUI at some point and see what the order of operations for events is. I did a little finagling to get CraftBagExtended working so possibly could do the same thing for BetterUI.

**Comment by Kesmy** [comment]
If rockingdice doesn't put work into BetterUI, it has otherwise been abandoned, and has some fundamental problems with the way it handles inventory and banking. I'd rank this issue extremely low-priority unless BUI development becomes very active again.

(this comment meant mostly for anyone who finds this thread in the future)

**Comment by ArtOfShred** [comment]
Fixed in 5.2.3 update!
