### ISSUE TITLE
anyway to move this stuff...

### ISSUE THREAD

**Issue by Madman-08** [DakJaniels/LuiExtended#64]
The quest log and the status bar are where I'd normally put a mini-map. I can't see a way to move (or just hide) them at all... can this be added?
https://imgur.com/a/82VAl

I should add - I really like what you've done! Great UI. Just hoping to make it a bit more flexible for my personal taste :)  - I was using AUI but it was throwing errors and not being updated. So really glad you guys are picking up the reigns!

**Comment by ArtOfShred** [comment]
Quest log is not part of LUI. You could grav the addon Azurah to move that.

As far as the Info Panel you can unlock that in the main LUI Extended
settings menu. Theres a dropdown for the Info Panel settings there.

I might add a component in the future to unlock default UI elements but no
current plans to do so.

**Comment by Madman-08** [comment]
I thought I combed through all the interface options, missed that one. - Thanks!
