### ISSUE TITLE
Next Release Update Preparation

### ISSUE THREAD

**Issue by ArtOfShred** [DakJaniels/LuiExtended#70]
**General:**
* [x] Add color configuration option to timestamps (default still matches pChat default)
* [x] Add PrintToChat to chat tabs of player choice into base menu options
* [x] Fix hook for Skill Windows (to not throw errors with Skills Advisor) + add custom icon/name support to Skills Advisor.
* [x] Switch any localized player name (raw, formatted, unformatted) into namespace for LUIE instead of in individual components.
* [x] Add Window Popup with ChangeLog on initial load when version number is updated.
* [x] Add Keybinds support for some basic slash commands that require no additional input (assistants, /home, /ready, /regroup)

**Info Panel:**
* [x] Fix issue where frame appears over other UI elements due to not being added to Scene.
* [x] Fix fields being cutoff.

**Unit Frames:**
* [x] Changing Player Frame method (from Stacked, Pyramid, or Default Style) also resets Group/Raid/Boss frames. Add a menu flag to stop this from happening.
* [x] Add % slider for low resource warnings - Independent for each type possibly?
* [x] Add option to change opacity of Shield Bar
* [x] Add priority option to choose whether player Title or player AVA Rank Name takes precedence.
* [x] Add separate option for the display of AVA Rank Number & Icon.

**Combat Info:**
* [x] Add sound option + choices for Ability procs.
* [x] Add font/size/position customization options for Ultimate % tracking label
* [x] Fix order of operations for Ultimate Tracking Label being removed when bar highlight for an Ultimate ability is enabled - currently the label fades after the new one appears causing momentary overlap.
* [x] Add option to toggle bar highlight on/off for secondary effects triggered by instant cast abilities (Major Savagery from Biting Jabs, Mana restore from Honor the Dead, etc...)

**Combat Text:**
* [x] Add option to abbreviate numbers to k
* [x] Add opacity option
* [x] Add toggle option for aura detection based Alert events to differentiate ID's commonly used in overworld vs dungeons (or check for group status as a lazy solution to stop as much spam from going off).

**Buffs and Debuffs:**
* [x] Fix Roar of Alkosh set - Remove name change for linebreaker (Possibly add new icon? Maybe not needed)
* [x] Cleanup the "NoRefresh" conditional nonsense in OnCombatEventIn and OnCombatEventOut, should no longer be needed. <- Might need to check a few abilities like stagger, etc - could add those result types in to allow them to pass through the filters.
* [x] Add option to Display Extra buff icons for effects like Dragon Blood, Restoring Focus, etc...
* [x] Add option to consolidate major/minor buffs from certain effects like Dragon Blood, Restoring Focus, etc...
* [x] Add manual blacklist by ID or name input field.

**Chat Announcements:**
* [x] Crafting Messages - Add support for upgrading equipped items (new base game feature)
* [x] Update icon + default color for Outfit Change tokens (since new icon was added)
* [x] Fix Fighter's Guild throttled rep printer not displaying reputation earned.
* [x] Look into hooking Guild Heraldry function to resolve correct gold value for initial Heraldry cost/change cost. Currently set to a flat value of 1000.
* [x] Buy horse from Stable - any way to generate a collectible link here instead of a normal string. Maybe add a check/table to look for Horse names to replace with collectibleId link.
* [x] Collectible Messages (PTS) - Find a way to hook into the new callback function to restore functionality here.

**Comment by psypanda** [comment]
Changed the milestone since there will be another release of LUI before Summerset
