### ISSUE TITLE
Info Panel update

### ISSUE THREAD

**Issue by psypanda** [DakJaniels/LuiExtended#71]
Module:
- Info Panel

Rework the Info Panel module and add new features and styling

Options:
- [ ] Time
- [ ] FPS
- [ ] Ping
- [ ] Zone (Current)
- [ ] Level
- [ ] Bag Space (Used/Total)
- [ ] Soulgems
- [ ] Gold / AP / TV / WV / TransmuteStones
- [ ] Alliance Rank
- [ ] XP (Current/Needed)

Maybe:
- [ ] Race/Class/Name
- [ ] Horse training timer
- [ ] Reasearch timers
- [ ] WW/Vampire bar
- [ ] Armor status (repair Gold value)
- [ ] Bank Space
- [ ] Lockpicks
- [ ] Tamriel time
- [ ] Fence/Launder info
- [ ] Skyshards (Collected/Total)
- [ ] Achievement points

**Comment by thesimonho** [comment]
wykkyd toolbar has a lot of those features implemented in case you want to take a look at their implementation: https://www.esoui.com/downloads/info737-WykkydToolbar.html

**Comment by ArtOfShred** [comment]
The Elder Bar (https://www.esoui.com/downloads/info2099-TheElderBar.html) is pretty much everything I wanted to do here, including drag and drop elements.

I feel no need to reinvent the wheel now that something really solid exists, so shelving this concept. I may add a few minor things to the Info Panel at some point, I know some people enjoy the compact design of the LUIE panel.
