### ISSUE TITLE
Add option for old style PrintToChat with all tab printing

### ISSUE THREAD

**Issue by ArtOfShred** [DakJaniels/LuiExtended#78]
NOTE: These options will be removed in the future if I ever get the chance to update pChat:
* [ ] Add Dropdown menu to select print to all tabs or use individual printing.
* [ ] Add toggle option to enable passthrough to pChat for saving chat to restore.
* [ ] Clean up menu and add header.

**Comment by psypanda** [comment]
Update to pChat is probably not needed but adding the possibility to change messages sent through `d()` and `CHAT_SYSTEM:AddMessage()` to [libChat2](http://www.esoui.com/downloads/info740-libChat2.html) would be really nice.
![libChat2](https://puu.sh/A8feD/fecf846808.png)
