### ISSUE TITLE
Name bug on costom Unitframe when i use Chinese localized addon

### ISSUE THREAD

**Issue by TeamZaobi** [DakJaniels/LuiExtended#83]
![image](https://user-images.githubusercontent.com/37039584/39406960-7d3fb11a-4bf1-11e8-9b42-ac8e6f37e2c4.png)

that text works fine in other ui addons, but Lui. I loved Lui , so if u can fixed this , i ll be very gratful for u

**Comment by psypanda** [comment]
I think I found the problem and will push a fix soon. Expect it to be fixed with the next release of LUI for Summerset
