### ISSUE TITLE
Minor Update preparation (Possibly part of Murkmire API bump or next update)

### ISSUE THREAD

**Issue by ArtOfShred** [DakJaniels/LuiExtended#90]
* [x] Create a temporary workaround for Mounted Buff & Mount Stamina Bar not toggling off when dismounting via crouch or hard dismount until EVENT_MOUNTED_STATUS_CHANGED is fixed.
* [x] Fix Group/Raid frames not coloring correctly if no role is detected (in the case of being in a BG or as a fallback)
* [x] Fix "looted" message sometimes reverting to "received" when rapidly looting items. Need to use a throttle function with a longer reset then standard 50ms buffer printer delay.
* [x] Fix functionality of - "If custom group frames are unused, then this raid frame will also be used for small groups."
* [x] Disable normal Attribute Bars & Frames as the default setting if possible.
* [x] Add option to color Target bar by Class (should take priority over Reaction based color when both are enabled)
* [x] Hide info panel during UI menus + dialogues
* [x] Add group member death notification to Combat Text.

**Comment by Tiara-Ra** [comment]
Can u make 1 more cosmetic change? It possible change color on default player bar as on screen? 
https://imgur.com/a/jW3BCmJ
I dont want install 1 more addon for so little changes. Ty!

**Comment by ArtOfShred** [comment]
I don't have any intention of doing any art changes for the base UI frames. DarkUI and various other skin addons handle that perfectly well.
