### ISSUE TITLE
Set-based permanent buffs are not cleared from the prominent buff tracker when switching zones

### ISSUE THREAD

**Issue by jrobijn** [DakJaniels/LuiExtended#91]
When you're wearing a set that gives you a permanently active buff which you are tracking in your prominent buff tracker, a copy of that buff keeps getting added to your prominent buff tracker every time you port to a different zone. Seems like it rechecks your permanent buffs every time you enter a new zone, but forgets to remove the previous instance of that buff.

This stacks up, so after porting to 4 different zone youll have 4 buffs stuck in your buff tracker. The 4th can be removed just fine by unslotting the gear set in question, but the other 3 are stuck in the tracker.

For example, this happens with the Major Resolve buff when wearing Mighty Chudan. Obviously you dont need to have permanent buffs in your buff tracker in the first place, but depending on the trial you're running you might want to wear different sets and not be forced to change your prominent buff settings.
![screenshot_20181103_115503](https://user-images.githubusercontent.com/9803186/47951769-9a680780-df65-11e8-81e6-86f0b9e8961e.png)

**Comment by ArtOfShred** [comment]
Thanks for letting me know, this one is an easy fix. Resolved!
