### ISSUE TITLE
Hide UI Fails in Player Homes

### ISSUE THREAD

**Issue by Rykoth** [DakJaniels/LuiExtended#99]
**Describe the bug**
When I go to take screenshots in my player homes, I'll have various parts of the UI that do not hide like the info on the upper right and group frames.

**Other installed AddOns**
The only add ons I could think might cause an issue is essential housing tools.

**Comment by psypanda** [comment]
I think I don't understand this.
Could you please provide more info on what you expect to happen when you enter your home? 
In case you just want to hide everything from your UI to take screenshots, there is a keybinding you can set to hide all elements of the UI.
![screenshot](https://i.imgur.com/s99bogU.jpg)
For me this hides all UI elements
![screenshot](https://i.imgur.com/6XB95NA.jpg)

**Comment by Rykoth** [comment]
I have hide UI bound to F12. It used to work but recently when I do it, it leaves the stuff in the upper right hand corner, or if I'm in a group, the unit frames remain. It's ONLY in player homes.

**Comment by psypanda** [comment]
Alright I figured it out. The problem only exists if you have [Essential Housing Tools](https://www.esoui.com/downloads/info1959-EssentialHousingTools.html) installed.
I'll see what I can do. Thank you for your report.

**Comment by ArtOfShred** [comment]
Thanks for reporting this, I took a look yesterday and unfortunately it might be a bit of an adventure to fix. I may need to reach out to Essential Housing Tools author as there's some code in there causing some conflict with LUIE.

**Comment by psypanda** [comment]
Pinging @Rykoth since the Essential Housing Tools version `2019-03-23 - 12.0.0, 12.0.1` seems to include a fix for this:  

>The Toggle UI function will now hide additional windows created by LUI Extended;
however, some windows may continue to remain visible due to limitations of what
elements of other add-ons can be hidden by EHT.

Is everything behaving now as desired?

**Comment by ArtOfShred** [comment]
Update: Long term buffs & Info Panel still show with EHT running. Fyrakin's minimap also shows for the record too (oddly flashes on and off periodically).

I may try to look into this, hard to say why this is happening, maybe layering, maybe the code in EHT has some support for LUIE now added, will have to check.

**Comment by ArtOfShred** [comment]
Update 2: EHT uses a specific override to hide LUIE unit frames. I'll have to add the buffs & info panel into the LUIE namespace and request they are added.

EDIT: Added Info Panel & Buffs & Debuffs controls into LUIE namespace. Will request an update to EHT when I'm closer to release. Also might consider stacking all these into LUIE namespace under something like LUIE.Frames.

**Comment by ArtOfShred** [comment]
Going to close this issue since I've prepared everything necessary for EHT compatibility, I'll content the author close to or at release so this is hopefully addressed shortly after.
